# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactory',
            options={'verbose_name': '\u8bbe\u5907\u5382\u5546', 'verbose_name_plural': '\u8bbe\u5907\u5382\u5546'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u7528\u6237\u4fe1\u606f', 'verbose_name_plural': '\u7528\u6237\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='manufactory',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5382\u5546\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='manufactory',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u5382\u5546'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='support_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u652f\u6301\u7535\u8bdd'),
        ),
    ]
