# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20160729_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='asset_count',
            field=models.IntegerField(default=0, max_length=16, verbose_name='\u8d44\u4ea7\u6570\u91cf'),
        ),
    ]
